services:
  # Frontend (Next.js)
  - type: web
    name: careermate-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://careermate-backend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Backend (Node.js)
  - type: web
    name: careermate-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: careermate-mongodb
    databaseName: careermate
    user: careermate_user
